name: Data Pipeline Feedback 

on:
  push:
    branches:
    - main
  paths:
      - data/**
      - project/**
    
jobs:
  pipeline-feedback:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pandas
        pip install SQLAlchemy
        pip install pysqlite3
    
    # Run exercise feedback
    - name: Pipeline feedback
      run: sh tests.sh
      working-directory: project
