name: Exercise Feedback 2

on:
  push:
    branches:
    - main

jobs:
  exercise-feedback:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main/project
      

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    # Run exercise feedback
    - name: Pipeline feedback
      run: python ./exercises/exercise2.py
