name: Pipeline feedback

on:
  push:
    branches:
    - main

jobs:
  pipeline-feedback:
    runs-on: ubuntu-latest
    steps:
    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
   
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Run exercise feedback
    - name: Pipeline feedback
      run: pytest -q ./project/test_class.py
