name: Pipeline feedback

on:
  push:
    branches:
    - main

jobs:
  pipeline-feedback:
    runs-on: ubuntu-latest
    steps:

    # Run exercise feedback
    - name: Pipeline feedback
      run: ./project/tests.sh
