name: Pipeline feedback

on:
  push:
    branches:
    - main

jobs:
  pipeline-feedback:
    runs-on: ubuntu-latest
    steps:
    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
  
   # Install dependencies
   - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  pytest

    # Run exercise feedback
    - name: Pipeline feedback
      run: ./project/tests.sh
